Added custom actions so that the user can define commands to open one or more files
0x90d/videoduplicatefinder pull request #248
Opened 2021-12-04 19:42 UTC by Maltragor

- It will be possible to define your own command lines for the four actions: 
  - Open
  - Open in folder
  - Open multiple 
  - Open multiple in folder

- If setting a custom open / open in folder command, the default open action is replaced.
-> This allowes to select your favourite player or file manager (e.g. with file selection support on linux)
The multi open actions are used to open whole groups or multiple selected files.
(Open multiple in folder -> some file managers like nemo are able to open multiple directories in tabs)

- There will be two new entries in the context menu to open a group (player + in folder)
  - Only visible if the corresponding multi open command is defined

- The DoubleTapped event on the thumbnails will open all selected files (if a multi open command is defined)

- Pressing enter will open the selected file(s)
  - If the thumbnail column is focused, the open command is executed
  - If the filename column is focused, the open in folder command is executed
  - In combination with the modifier keys for row selection the workflow is faster and easier (in my opinion) than always going via the context menu

- Commands:
  - Simple form: `nemo`  -> The selected files are appended
  - Using the placeholder:  `nemo %f --tabs` -> '%f' will be replaced with the selected files
  - _Exampe: Show the selected files in terminal window: `cmd /c "echo %f & pause"`_
  - If execution fails, a logging entry will be created

2021-12-05 03:50 UTC, Symbai requested changes
Very good job, just small code-style things I can change myself later. Only using Reflection is something I would like to avoid

2021-12-05 03:50 UTC, Symbai commented on VDF.GUI/ViewModels/MainWindowVM.cs
> +		}
Avalonia is currently doing some work to make trimming and AOT possible which I would like to use then. But using Reflection is not possible in AOT.

2021-12-05 03:53 UTC, merged

2022-08-11 21:10 UTC, Kutabarie commented
Can you please explain how this would work in Windows? I still can't open more than 1 file at once.

2022-08-11 23:00 UTC, Maltragor commented
The mechanism is identical in Windows and Linux. 
Since you did not describe in which application you want to open the files, I can only describe the functionality in general.
And of course the application you have chosen must be able to open multiple files passed as command line parameters!

For demonstration purposes I have chosen cmd.exe as application to simply output the filenames in a console window: 
`cmd /c echo %f & pause`
(While executing the command `%f ` gets replaced by the selected file names)

In the following I used the `OpenMultipleInFolder` command:
![Unbenannt3](https://user-images.githubusercontent.com/36803696/184253147-7ca5dc46-eaaa-4783-97fd-a56daaaaf43b.png)

The command is executed **either**:
![Unbenannt](https://user-images.githubusercontent.com/36803696/184253340-fb9a8bb0-4017-4ecc-9f98-7df8aa173d7b.png)
-> Select multiple rows 
-> right click on one of the selected rows 
-> click on "open in folder"

**Or**:
![Unbenannt2](https://user-images.githubusercontent.com/36803696/184253523-cca940e7-a196-4ffb-a56f-23ab7e399282.png)
-> Select multiple rows 
-> the active selected cell must belong to the **path** column (image2.jpg with white rectangle) 
-> press _enter_ on the keyboard to execute the command

This will execute the configured `cmd /c echo %f & pause` command line so that the file names are displayed in a console window:
![Unbenannt4](https://user-images.githubusercontent.com/36803696/184254317-fc2c5476-3a81-4bf6-aa9a-4836a5699c36.png)

----------------
Alternatively, the configurable `OpenMultiple` command will be called when:
-> Select multiple rows 
-> the active selected cell must belong to the **thumbnail** column
-> press _enter_ on the keyboard to execute the command

2022-08-12 22:37 UTC, Kutabarie commented
Thank you for the reply. I thought by default I would be able to open all the selected files using the default media player as if I have selected the files in Windows Explorer and pressed Enter, but I guess i'll have to learn if I can work it out if i'm able to use commands on my player. What I had in mind is that if I selected 3 files and pressed enter, it would open 3 windows of MPC or PotPlayer at once.

2022-08-13 04:15 UTC, Maltragor commented
> open all the selected files using the default media player as if I have selected the files in Windows Explorer and pressed Enter

Then you can use this as command:
`cmd /c for %x in (%f) do start "" "%~x"`

This will briefly open a console window, loop over all selected file names and opens each file with the default player
`cmd /c ` -> executes the subsequent parameters in cmd.exe
`%f`        -> file name placeholder of VDF. It will be replaced by VDF before calling the command
`for %x in ([parameter list]) do` -> A loop. Executes the subsequent command for each element of `[parameter list]` (accessible by `%x`) 
`start "" "%~x" `  -> `start` is a function of cmd.exe to open a file using the default application for the corresponding file type (or to execute a process detached)

-------------
If you want to use a specific player you could use this command:
`cmd /c for %x in (%f) do start "" "C:\Program Files\MPC-HC\mpc-hc64.exe" "%~x"`

Of course you would replace `C:\Program Files\MPC-HC\mpc-hc64.exe` by your desired application.
_(But keep the quotation marks. They are necessary to support paths and filenames with spaces)_


Alternatively you can save the following as text file with filename e.g. `RunPlayer.cmd` in your VDF root directory:
_(... and of course again change the player as desired ...)_
```
@echo off

set PLAYER="C:\Program Files\MPC-HC\mpc-hc64.exe"

for %%x in (%*) do (
  start "" %PLAYER% "%%~x"
)
```
and only insert `RunPlayer.cmd %f ` as command in VDF
_Functionally it is identical to the previous variant, only divided differently, so that in VDF the whole command does not have to be entered._

2023-01-21 22:14 UTC, Kutabarie commented
Thank you so much, so pretty much completes my experience with this program!