Update Avalonia to 0.9.12 so it can work with ubuntu 20.04
0x90d/videoduplicatefinder pull request #96
Opened 2020-08-08 14:16 UTC by mimran1980

Getting seg faults in ubuntu 20.04, updated avalonia which seems to resolve this issue.

2020-08-09 07:12 UTC, olivierchoquet commented
I confirm that the version of mimran works (https://github.com/mimran1980/videoduplicatefinder).
The PR can be merged !

2020-09-03 18:24 UTC, 0x90d requested changes
Looks good to me, please see my comments and add the changes so I can merge, thanks!

2020-09-03 18:24 UTC, 0x90d commented on VideoDuplicateFinderLinux/DuplicateViewModel.xaml
> +             x:Class="VideoDuplicateFinderLinux.DuplicateViewModel"
Nit: format spaces

2020-09-03 18:24 UTC, 0x90d commented on VideoDuplicateFinderLinux/MessageBoxView.xaml.cs
> +		}
Why was this added?

2020-09-03 18:24 UTC, 0x90d commented on VideoDuplicateFinderLinux/VideoDuplicateFinderLinux.csproj
> +-->
Why was this added? Please remove

2020-09-03 18:24 UTC, 0x90d commented on VideoDuplicateFinderLinux/VideoDuplicateFinderLinux.csproj
> +
Remove

2021-02-16 16:14 UTC, scruffynerf commented
any chance of actually rolling this in, so Linux works in the binary release again?

BTW, it won't build with Avalonia 0.10, Serilog not longer supported.  You have to use 0.9.12

2021-08-03 10:09 UTC, 0x90d commented
Thanks for your contribution and sorry for not having this reviewed. Closing because this refers to outdated VDF Version 2

2021-08-03 10:09 UTC, closed without merging